BEGIN;

CREATE TABLE user (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	sid VARCHAR(32) NOT NULL,
	first_name VARCHAR(25) NOT NULL,
	last_name VARCHAR(35) NOT NULL,
	login VARCHAR(15) NOT NULL,
	password VARCHAR(65) NOT NULL,
	email VARCHAR(30) NOT NULL,
	type INT(4) NOT NULL,
	UNIQUE (sid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE 'user' CHANGE COLUMN password VARCHAR(80) NOT NULL;


COMMIT;